package io.github.nashcrash.autorest.processor.generator;

import com.squareup.javapoet.*;
import io.github.nashcrash.autorest.processor.dto.GenericRestApiDTO;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

import javax.lang.model.element.Modifier;

public class AutoResourceGenerator {

    public JavaFile generateResource(GenericRestApiDTO genericRestApiDTO) {
        String entityName = genericRestApiDTO.getEntityName();
        String basePath = genericRestApiDTO.getBasePath();
        TypeName dtoType = genericRestApiDTO.getDtoType();
        TypeName entityType = genericRestApiDTO.getEntityType();
        boolean isReactive = genericRestApiDTO.isReactive();
        String packageName = genericRestApiDTO.getPackageName();

        ParameterizedTypeName superClass = null;
        if (isReactive) {
            superClass = ParameterizedTypeName.get(ClassName.get("io.github.nashcrash.autorest.common.entity.reactive", "AbstractEntityReactiveResource"), entityType, dtoType);
        } else {
            superClass = ParameterizedTypeName.get(ClassName.get("io.github.nashcrash.autorest.common.entity.reactive", "AbstractEntityRestResource"), entityType, dtoType);
        }

        // 1. Class Definition
        TypeSpec.Builder resourceClass = TypeSpec.classBuilder(entityName + "Resource")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(genericRestApiDTO.getGeneratedAnnotationSpec())
                .addAnnotation(ClassName.get("lombok.extern.slf4j", "Slf4j"))
                .addAnnotation(AnnotationSpec.builder(Path.class).addMember("value", "$S", basePath).build())
                .addAnnotation(AnnotationSpec.builder(Produces.class).addMember("value", "$T.APPLICATION_JSON", MediaType.class).build())
                .addAnnotation(AnnotationSpec.builder(Consumes.class).addMember("value", "$T.APPLICATION_JSON", MediaType.class).build())
                .addAnnotation(ClassName.get("jakarta.enterprise.context", "ApplicationScoped"));

        // 2. Class implementation
        resourceClass.superclass(superClass);

        return JavaFile.builder(packageName, resourceClass.build())
                .addFileComment("AUTO-GENERATED BY GENERIC-REST-API - DO NOT EDIT")
                .build();
    }
}
