package io.github.nashcrash.autorest.processor.generator;

import com.squareup.javapoet.*;
import io.github.nashcrash.autorest.common.entity.AccumulatorType;
import io.github.nashcrash.autorest.common.entity.FieldPair;
import io.github.nashcrash.autorest.processor.dto.AggregateDTO;
import io.github.nashcrash.autorest.processor.dto.GenericRestApiDTO;
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.core.MediaType;
import org.eclipse.microprofile.openapi.annotations.Operation;

import javax.lang.model.element.Modifier;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class AutoResourceGenerator {

    public JavaFile generateResource(GenericRestApiDTO genericRestApiDTO) {
        String entityName = genericRestApiDTO.getEntityName();
        String basePath = genericRestApiDTO.getBasePath();
        TypeName dtoType = genericRestApiDTO.getDtoType();
        TypeName entityType = genericRestApiDTO.getEntityType();
        boolean isReactive = genericRestApiDTO.isReactive();
        String packageName = genericRestApiDTO.getPackageName();

        ParameterizedTypeName superClass = null;
        if (isReactive) {
            superClass = ParameterizedTypeName.get(ClassName.get("io.github.nashcrash.autorest.common.entity.reactive", "AbstractEntityReactiveResource"), entityType, dtoType);
        } else {
            superClass = ParameterizedTypeName.get(ClassName.get("io.github.nashcrash.autorest.common.entity.reactive", "AbstractEntityRestResource"), entityType, dtoType);
        }

        // 1. Class Definition
        TypeSpec.Builder resourceClass = TypeSpec.classBuilder(entityName + "Resource")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(genericRestApiDTO.getGeneratedAnnotationSpec())
                .addAnnotation(ClassName.get("lombok.extern.slf4j", "Slf4j"))
                .addAnnotation(AnnotationSpec.builder(Path.class).addMember("value", "$S", basePath).build())
                .addAnnotation(AnnotationSpec.builder(Produces.class).addMember("value", "$T.APPLICATION_JSON", MediaType.class).build())
                .addAnnotation(AnnotationSpec.builder(Consumes.class).addMember("value", "$T.APPLICATION_JSON", MediaType.class).build())
                .addAnnotation(ClassName.get("jakarta.enterprise.context", "ApplicationScoped"));

        // 2. Class implementation
        resourceClass.superclass(superClass);

        // 3. Add aggregate methods
        if (genericRestApiDTO.getAggregate() != null) {
            for (AggregateDTO aggregateDTO : genericRestApiDTO.getAggregate()) {
                resourceClass.addMethod(generateAggregateGet(genericRestApiDTO, aggregateDTO));
                resourceClass.addMethod(generateAggregatePost(genericRestApiDTO, aggregateDTO));
            }
        }

        return JavaFile.builder(packageName, resourceClass.build())
                .addFileComment("AUTO-GENERATED BY GENERIC-REST-API - DO NOT EDIT")
                .build();
    }

    private MethodSpec generateAggregateGet(GenericRestApiDTO genericRestApiDTO, AggregateDTO aggregateDTO) {
        TypeName returnType = genericRestApiDTO.isReactive() ?
                wrapToUni(ParameterizedTypeName.get(ClassName.get(List.class), aggregateDTO.getDtoTypeName())) :
                ParameterizedTypeName.get(ClassName.get(List.class), aggregateDTO.getDtoTypeName());
        return MethodSpec.methodBuilder(checkMethodName(aggregateDTO.getName(), "aggregate") + "Get")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(ClassName.get("jakarta.ws.rs", "GET"))
                .addAnnotation(AnnotationSpec.builder(Path.class).addMember("value", "$S", aggregateDTO.getPath()).build())
                .addAnnotation(AnnotationSpec.builder(Operation.class)
                        .addMember("summary", "$S", "Aggregate by " + aggregateDTO.getDtoTypeElement().getSimpleName() + " with filtering and pagination").build())
                .addParameter(ParameterSpec.builder(String.class, "query").addAnnotation(AnnotationSpec.builder(QueryParam.class).addMember("value", "$S", "query").build()).build())
                .addParameter(ParameterSpec.builder(String[].class, "orderBy").addAnnotation(AnnotationSpec.builder(QueryParam.class).addMember("value", "$S", "orderBy").build()).build())
                .addParameter(ParameterSpec.builder(String[].class, "orderDirection").addAnnotation(AnnotationSpec.builder(QueryParam.class).addMember("value", "$S", "orderDirection").build()).build())
                .addParameter(ParameterSpec.builder(int.class, "page").addAnnotation(AnnotationSpec.builder(QueryParam.class).addMember("value", "$S", "page").build()).build())
                .addParameter(ParameterSpec.builder(int.class, "limit").addAnnotation(AnnotationSpec.builder(QueryParam.class).addMember("value", "$S", "limit").build()).build())
                .returns(returnType)
                .addStatement("return service.aggregate(\n" +
                                "    $L,\n" + // fieldsBlock
                                "    $L,\n" + // accumulatorsBlock
                                "    $T.builder().query(query).orderBy(orderBy).orderDirection(orderDirection).page(page).limit(limit).build(),\n" +
                                "    $T.class)",
                        generateFieldsBlock(aggregateDTO.getGroupBy()),
                        generateAccumulatorsBlock(aggregateDTO.getAggregateBy()),
                        ClassName.get("io.github.nashcrash.autorest.common.entity", "FindDTO"),
                        aggregateDTO.getDtoTypeName()
                )
                .build();
    }

    private MethodSpec generateAggregatePost(GenericRestApiDTO genericRestApiDTO, AggregateDTO aggregateDTO) {
        TypeName returnType = genericRestApiDTO.isReactive() ?
                wrapToUni(ParameterizedTypeName.get(ClassName.get(List.class), aggregateDTO.getDtoTypeName())) :
                ParameterizedTypeName.get(ClassName.get(List.class), aggregateDTO.getDtoTypeName());
        return MethodSpec.methodBuilder(checkMethodName(aggregateDTO.getName(), "aggregate") + "Post")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(ClassName.get("jakarta.ws.rs", "POST"))
                .addAnnotation(AnnotationSpec.builder(Path.class).addMember("value", "$S", aggregateDTO.getPath()).build())
                .addAnnotation(AnnotationSpec.builder(Operation.class)
                        .addMember("summary", "$S", "Aggregate by " + aggregateDTO.getDtoTypeElement().getSimpleName() + " with filtering and pagination").build())
                .addParameter(ParameterSpec.builder(ClassName.get("io.github.nashcrash.autorest.common.entity", "FindDTO"), "findDto").build())
                .returns(returnType)
                .addStatement("return service.aggregate(\n" +
                                "    $L,\n" + // fieldsBlock
                                "    $L,\n" + // accumulatorsBlock
                                "    findDto,\n" +
                                "    $T.class)",
                        generateFieldsBlock(aggregateDTO.getGroupBy()),
                        generateAccumulatorsBlock(aggregateDTO.getAggregateBy()),
                        aggregateDTO.getDtoTypeName()
                )
                .build();
    }

    private CodeBlock generateAccumulatorsBlock(Map<AccumulatorType, FieldPair> aggregateBy) {
        ClassName fieldPairTypeClass = ClassName.get("io.github.nashcrash.autorest.common.entity", "FieldPair");
        ClassName accumulatorTypeClass = ClassName.get("io.github.nashcrash.autorest.common.entity", "AccumulatorType");
        CodeBlock.Builder accumulatorsBuilder = CodeBlock.builder().add("$T.of(", ClassName.get(Map.class));

        List<CodeBlock> pieces = new ArrayList<>();
        for (Map.Entry<AccumulatorType, FieldPair> entry : aggregateBy.entrySet()) {

            pieces.add(CodeBlock.of("$T.$L, $T.of($S, $S)",
                    accumulatorTypeClass,
                    entry.getKey().name(),
                    fieldPairTypeClass,
                    entry.getValue().getOriginalField(),
                    entry.getValue().getTargetField()
            ));
        }
        return accumulatorsBuilder.add(CodeBlock.join(pieces, ", ")).add(")").build();
    }

    private CodeBlock generateFieldsBlock(List<FieldPair> groupBy) {
        ClassName fieldPairTypeClass = ClassName.get("io.github.nashcrash.autorest.common.entity", "FieldPair");
        CodeBlock.Builder fieldsBuilder = CodeBlock.builder().add("$T.of(", ClassName.get(List.class));

        List<CodeBlock> pieces = new ArrayList<>();
        for (FieldPair field : groupBy) {
            pieces.add(CodeBlock.of("$T.of($S, $S)", fieldPairTypeClass, field.getOriginalField(), field.getTargetField()));
        }
        return fieldsBuilder.add(CodeBlock.join(pieces, ", ")).add(")").build();
    }

    public String checkMethodName(String name, String defaultName) {
        if (name == null) return defaultName;
        name = name.replaceAll("[^a-zA-Z0-9]", "");
        return name.isEmpty() ? defaultName : name;
    }

    /**
     * Avvolge un TypeName esistente in un io.smallrye.mutiny.Uni.
     * Esempio: String -> Uni<String>
     */
    public TypeName wrapToUni(TypeName typeToWrap) {
        ClassName uniRaw = ClassName.get("io.smallrye.mutiny", "Uni");
        TypeName boxedType = typeToWrap.isPrimitive() ? typeToWrap.box() : typeToWrap;
        return ParameterizedTypeName.get(uniRaw, boxedType);
    }
}
